sonar.organization=mibipret
sonar.projectKey=MiBiPreT_mibisite
sonar.host.url=https://sonarcloud.io
sonar.sources=mibisite/
sonar.tests=tests/
sonar.links.homepage=https://github.com/MiBiPreT/mibisite
sonar.links.scm=git@github.com:MiBiPreT/mibisite
sonar.links.issue=https://github.com/MiBiPreT/mibisite/issues
sonar.links.ci=https://github.com/MiBiPreT/mibisite/actions
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-result.xml
sonar.python.pylint.reportPaths=pylint-report.txt
